service: splatnet2statink

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  memorySize: 512
  timeout: 30
  region: ap-northeast-1

functions:
  post_unuploaded_battles:
    handler: handler.main
    events:
      - schedule: cron(0/15 * * * ? *)

package:
  exclude:
    - .*
    - __pycache__/**
    - venv/**
    - node_modules/**
    - serverless.yml
    - package*.json
    - requirements.txt
    - README.md
    - LICENSE
