service: splatnet2statink

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  memorySize: 512
  timeout: 30
  stage: prod
  region: ap-northeast-1

functions:
  post_unuploaded_battles:
    handler: handler.main
    events:
      - name: at-every-schedule-rotation
      - description: At every schedule rotation.
      - schedule: cron(0 */2 * * ? *)

package:
  exclude:
    - .*
    - __pycache__/**
    - venv/**
    - node_modules/**
    - serverless.yml
    - package*.json
    - requirements.txt
    - README.md
    - LICENSE
